### ISSUE TITLE
Please add retry mechanizm

### ISSUE THREAD

**Issue by andreieuganox** [ScrapingBee/scrapingbee-node#5]
Due to the fact that there were many cases when Scrapingbee returned 500 or the source server returned 5XX errors, can you please accommodate the retry mechanism in SDK? 
As you use Axios, it is just a few lines https://www.npmjs.com/package/axios-retry:
```
++ import axiosRetry from 'axios-retry';
.....
++ axiosRetry(axios, { retries: 3 });
```

For sure, please consider passing 3rd parameter to ScrapingBeeClient so options can be passed to Axios-retry. But it will already be a great improvement if retries are handled automatically.

Hope to see it in SDK soon.

**Comment by daolf** [comment]
Hi there, and thank you for your feedback.

The package will be updated soon, we will add this feature!

Cheers

Pierre
