### ISSUE TITLE
Axios timeout

### ISSUE THREAD

**Issue by andreieuganox** [ScrapingBee/scrapingbee-node#7]
Problem:
Observed that from time to time, the requests to the ScrapingBee hang for many minutes. This seems to be caused by some infrastructure issues. At the same time, Axios' default timeout is `0` - indefinite. That causes the request to hang before the server returns the error that `socket hang-up`. this situation can be easily avoided by setting the timeout to the Axios requests. It would be, in some cases, beneficial to control this timeout, therefore adding it to the config.

Please consider the improvement that seems to be a one-liner.

**Comment by maxpain** [comment]
The same problem
